[versions]
slf4j-version = "2.0.0-alpha6"
log4j2-version = "2.17.1"
log4j2-slf4j-version = "2.17.1"
sshj-version = "0.32.0"
picocli-version = "4.6.3"
jackson-version = "2.13.1"
raksrinana-utils-version = "15.0.3"
commons-io-version = "2.11.0"
progressbar-version = "0.9.3"
jetbrains-annotations-version = "23.0.0"
commons-collections-version = "4.4"

shadow-version = "7.1.2"
names-version = "0.42.0"
lombok-version = "6.4.1"

[libraries]
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-version" }
log4j2-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j2-version" }
log4j2-slf4j = { group = "org.apache.logging.log4j", name = "log4j-slf4j18-impl", version.ref = "log4j2-slf4j-version" }
sshj = { group = "com.hierynomus", name = "sshj", version.ref = "sshj-version" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli-version" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson-version" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-version" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-version" }
raksrinana-utils-base = { group = "fr.raksrinana", name = "utils.base", version.ref = "raksrinana-utils-version" }
raksrinana-utils-config = { group = "fr.raksrinana", name = "utils.config", version.ref = "raksrinana-utils-version" }
commonsIo = { group = "commons-io", name = "commons-io", version.ref = "commons-io-version" }
commonsCollections = { group = "org.apache.commons", name = "commons-collections4", version.ref = "commons-collections-version" }
progressbar = { group = "me.tongfei", name = "progressbar", version.ref = "progressbar-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }


[bundles]
jackson = ["jackson-core", "jackson-annotations", "jackson-databind"]
raksrinanaUtils = ["raksrinana-utils-base", "raksrinana-utils-config"]
log4j2 = ["log4j2-core", "log4j2-slf4j"]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow-version" }
names = { id = "com.github.ben-manes.versions", version.ref = "names-version" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok-version" }
