[versions]
slf4j-version = "2.0.4"
log4j2-version = "2.19.0"
log4j2-slf4j-version = "2.19.0"
sshj-version = "0.34.0"
picocli-version = "4.7.0"
jackson-version = "2.14.1"
commons-io-version = "2.11.0"
progressbar-version = "0.9.5"
jetbrains-annotations-version = "23.0.0"
commons-collections-version = "4.4"
hikari-cp-version = "5.0.1"
h2-version = "2.1.214"
guava-version = "31.1-jre"

shadow-version = "7.1.2"
names-version = "0.44.0"
lombok-version = "6.5.1"
jib-version = "3.3.1"

[libraries]
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-version" }
log4j2-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j2-version" }
log4j2-slf4j = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j2-slf4j-version" }
sshj = { group = "com.hierynomus", name = "sshj", version.ref = "sshj-version" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli-version" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson-version" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-version" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-version" }
commonsIo = { group = "commons-io", name = "commons-io", version.ref = "commons-io-version" }
commonsCollections = { group = "org.apache.commons", name = "commons-collections4", version.ref = "commons-collections-version" }
progressbar = { group = "me.tongfei", name = "progressbar", version.ref = "progressbar-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikari-cp-version" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2-version" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava-version" }

[bundles]
jackson = ["jackson-core", "jackson-annotations", "jackson-databind"]
log4j2 = ["log4j2-core", "log4j2-slf4j"]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow-version" }
names = { id = "com.github.ben-manes.versions", version.ref = "names-version" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok-version" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib-version" }
