name: CI

on: [ push ]

env:
  APP_JAVA_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}
          cache: 'gradle'
      - uses: actions/cache@v3
        name: Cache gradle wrapper
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Set gradle permissions
        run: chmod +x gradlew
      - name: Check project
        run: ./gradlew check build
        env:
          GITHUB_USER: RakSrinaNa
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: shadow-jar
          path: build/libs/ftpfetcher-shaded.jar

  dropbox:
    runs-on: ubuntu-latest
    needs: build
    if:
      contains('refs/heads/main', github.ref)
    steps:
      - uses: actions/download-artifact@v3
        name: Download artifact
        with:
          name: shadow-jar
      - name: Deploy on Dropbox
        uses: deka0106/upload-to-dropbox@v2.0.1
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_DEPLOY_TOKEN }}
          src: "ftpfetcher-shaded.jar"
          dest: "/Documents/JARs/FTPFetcher.jar"
          mode: overwrite

  docker:
    runs-on: ubuntu-latest
    needs: build
    if:
      contains('refs/heads/main', github.ref)
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}
          cache: 'gradle'
      - name: Set gradle permissions
        run: chmod +x gradlew
      - name: Push on Docker repository
        run: ./gradlew jib -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKER_TOKEN }} -Djib.to.image="${{ secrets.DOCKER_IMAGE_REPO }}/rakambda/ftpfetcher:latest" -Djib.console=plain